set SQL_SAFE_UPDATES = 0;

DROP DATABASE IF EXISTS BDEX09;
CREATE DATABASE BDEX09;
USE BDEX09;


CREATE TABLE PESSOA(
IDPESSOA INT NOT NULL auto_increment
, NOME VARCHAR (120) NOT NULL
, DT_NACIMENTO DATE NOT NULL
, primary key (IDPESSOA)


);

CREATE TABLE CIN (
IDCIN INT NOT NULL AUTO_INCREMENT
, DT_EMISSAO DATE NOT NULL
, IDPESSOA INT NOT NULL UNIQUE
, primary key (IDCIN)
, foreign key (IDPESSOA) references PESSOA(IDPESSOA)


); 