DROP database IF EXISTS DBEXERCICIO02;

CREATE DATABASE DBEXERCICIO02;
USE DBEXERCICIO02;

CREATE TABLE NOTA (
	IDNOTA INT NOT NULL AUTO_INCREMENT
    , ALUNO varchar(120) NOT NULL
    , NOTA_BIMESTRE_01 decimaL(4,2) NOT NULL
    , NOTA_BIMESTRE_02 decimaL(4,2) NOT NULL
    , NOTA_BIMESTRE_03 decimaL(4,2) NOT NULL
    , NOTA_BIMESTRE_04 decimaL(4,2) NOT NULL
    , MEDIA decimaL(4,2) 
    , RESULTADO varchar(10) 
    , primary KEY (IDNOTA)
);