-- apagando o banco de dados caso exista --
DROP database IF exists DBEXERCICIO01;

-- CRIANDO O BRANCO DE DADOS 
CREATE DATABASE DBEXERCICIO01;

-- CONECTANDO AO BANCO DE DADOS 
USE DBEXERCICIO01;

-- CRIANDO AS TABELAS 
CREATE TABLE PESSOA (
	IDPESSOA INT NOT NULL AUTO_INCREMENT,
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    IDADE INT,
    PRIMARY KEY (IDPESSOA)
);