SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS BDEX10;
CREATE DATABASE BDEX10;
USE BDEX10;

CREATE TABLE CLIENTE (
ID_CLIENTE INT auto_increment
, NOME VARCHAR(120) NOT NULL
, primary key (ID_CLIENTE)
);

CREATE TABLE PRODUTO (
ID_PRODUTO INT AUTO_INCREMENT
, PRODUTO VARCHAR(120) NOT NULL
, QUANTIDADE INT NOT NULL
, ID_CLIENTE INT NOT NULL
, PRIMARY KEY (ID_PRODUTO)
, foreign key (ID_CLIENTE) references CLIENTE(ID_CLIENTE)
);